import {
  initAuth,
  authEvents$,
  authIdToken$,
  currentUser$,
  getAuthIDToken,
  getGithubCredentialFromResult,
  getSignInMethodsForEmail,
  isSignInWithEmailLink,
  linkWithFBCredential,
  linkWithFBCredentialFromAuthError,
  probableUser$,
  setDisplayName,
  setEmailAddress,
  setProviderInfo,
  signInUserWithGithub,
  signInUserWithGoogle,
  signInUserWithMicrosoft,
  signInWithEmail,
  signInWithEmailAndPassword,
  signInWithEmailLink,
  signOutUser,
  verifyEmailAddress,
  waitProbableLoginToConfirm,
} from "./auth/auth"

console.log("Loading Platform Stuff")

window.PLATFORM_CONFIG = {
  auth: {
    initAuth,
    getAuthIDToken,
    getGithubCredentialFromResult,
    getSignInMethodsForEmail,
    isSignInWithEmailLink,
    linkWithFBCredential,
    linkWithFBCredentialFromAuthError,
    setDisplayName,
    setEmailAddress,
    setProviderInfo,
    signInUserWithGithub,
    signInUserWithGoogle,
    signInUserWithMicrosoft,
    signInWithEmail,
    signInWithEmailAndPassword,
    signInWithEmailLink,
    signOutUser,
    verifyEmailAddress,
    waitProbableLoginToConfirm,
    authEvents$,
    authIdToken$,
    currentUser$,
    probableUser$,
  },
}
